### ISSUE TITLE
FIX YOUR README

### ISSUE THREAD

**Issue by Alina-dev-front** [alexyak1/Converter_HEIC#1]
HEIC IOS format. This format is not really convinient for Windows and Linux. <br />
With this bash script you can easily convert files from HEIC to JPG.

How to use?
1. Put the file to folder where is HEIC files are located.
2. cd to this folder in the terminal.
3. Run the file in the terminal with: <br /> bash converter_HEIC_jpg.sh

**Comment by alexyak1** [comment]
Thank you for contributing @Alina-dev-front
